### ISSUE TITLE
1942, 1943, and Devilfish RBF files saving to MRA path instead of Cores

### ISSUE THREAD

**Issue by RetroDriven** [MiSTer-devel/Updater_script_MiSTer#29]
I'm not sure if it's just me but every time I run the Updater it saves 1942, 1943, and Devilfish to the incorrect place. All other RBF files will get saved into **/_Arcade/Cores**. These three RBF files are getting saved to **/_Arcade/** for me. Is anyone else having this issue?

**Comment by djvelocitee** [comment]
I can confirm as well. I just ran this fresh 2 mins ago and had same results.

**Comment by Locutus73** [comment]
They go into **/_Arcade/**, instead of **/_Arcade/cores/** because they don't have any MRA file, so the updater thinks these specific RBF need an old style rbf+rom directory structure; it is intended.
With the current implementation rbf cores go into _Arcade/cores only when
a) the core repository contains a mra file
b) some other core previously downloaded (or an user put) a mra for that core (i.e. Pacman repo contains many mra files, such as Birdy.mra and Ms. Pacman.mra)

Try this: put yourself a DevilFish.mra file in the **/_Arcade/** dir and update again: DevilFish_20191015.rbf should be automatically moved into **/_Arcade/cores/**.
