### ISSUE TITLE
Linux version check before update

### ISSUE THREAD

**Issue by sorgelig** [MiSTer-devel/Updater_script_MiSTer#35]
Recent releases of Linux have file /MiSTer.version 
So it's better to check the version before update the Linux release.

**Comment by Locutus73** [comment]
Oh, nice, is it YYMMDD right? So I can use it in order to avoid the first Linux update which always happens on the very first update. In theory it can be avoided with a fake 0 byte file with the same name as the release rar in /media/fat/Scripts/,mister_updater/, but /MiSTer.version is more integrated and can work along with that, so I will use that too, very nice.
Thanks!

**Comment by sorgelig** [comment]
yes, YYMMDD

**Comment by Locutus73** [comment]
Implemented in version 4.0.2
https://github.com/MiSTer-devel/Updater_script_MiSTer/tree/87af0471ed682b831cb98b826f7efb8128768544

**Comment by Locutus73** [comment]
Implemented in version 4.0.2
https://github.com/MiSTer-devel/Updater_script_MiSTer/commit/87af0471ed682b831cb98b826f7efb8128768544
